FROM python:3.10-bookworm

RUN mkdir -v /usr/src/venv
COPY .venv /usr/src/venv/
RUN useradd -s /sbin/nologin word

COPY app /usr/src
WORKDIR /usr/src/
USER word
EXPOSE 8000
CMD ["/usr/src/venv/bin/python", "server.py"]