FROM python:3.10-bullseye

ARG VENV_PATH
RUN mkdir -v /usr/src/venv
COPY ${VENV_PATH} /usr/src/venv/
RUN useradd -s /sbin/nologin word

COPY . /usr/src
WORKDIR /usr/src/
USER word
EXPOSE 8000
CMD ["/usr/src/venv/bin/python", "server.py"]