name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  venv:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
      env:
        PIPENV_VENV_IN_PROJECT: 1
    - run: |
        
        pip3 install --upgrade pip
        pip3 install --user pipenv
        pipenv lock --pypi-mirror=https://pypi.org/simple
        pipenv sync --pypi-mirror=https://pypi.org/simple
        pipenv --venv
  build:

    runs-on: ubuntu-latest
    needs: venv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
      - name: prepare
        run: |
          cp app/Pipfile .
          sed -i 's#https://pypi.tuna.tsinghua.edu.cn/simple#https://pypi.org/simple#g' Pipfile
          mv app/Dockerfile_a Dockerfile
      - name: pipenv install
        id: venv
        run: |
          export PIPENV_VENV_IN_PROJECT=1
          pip3 install --user pipenv
          pipenv lock
          pipenv sync
          .venv/bin/pip install --upgrade pip
          ls -la

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

